In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [6]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [7]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [9]:
scaler.fit_transform(X)

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [11]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [12]:
model = Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [13]:
model.fit(X_train,y_train, batch_size=32, epochs=100, validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.6075 - loss: 4.6347 - val_accuracy: 0.5260 - val_loss: 3.6202
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5863 - loss: 2.3261 - val_accuracy: 0.5000 - val_loss: 2.4096
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5847 - loss: 1.8636 - val_accuracy: 0.5000 - val_loss: 2.0601
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6140 - loss: 1.6199 - val_accuracy: 0.4935 - val_loss: 1.7528
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6075 - loss: 1.3457 - val_accuracy: 0.6039 - val_loss: 1.4174
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6319 - loss: 1.1203 - val_accuracy: 0.4675 - val_loss: 1.3283
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6107 - loss: 1.0606 - val_accuracy: 0.4935 - val_loss: 1.1178
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6384 - loss: 0.9193 - val_accuracy: 0.6429 - val_loss: 1.0115
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6450 - loss: 0.8259 - val_accuracy: 0.6429 - val_loss: 0.9634
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6498 - loss: 0.8027 - val_accuracy: 0.5974 - val_loss: 1.0281
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.7859 - val_accuracy: 0.5974 - val_loss: 0.8920
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6661 - loss: 0.7367 - val_accuracy: 0.5844 - val_loss: 0.8726
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6645 - loss: 0.7729 - val_accuracy: 0.4935 - val_loss: 1.0017
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6417 - loss: 0.7834 - val_accuracy: 0.6169 - val_loss: 0.9751
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6336 - loss: 0.8038 - val_accuracy: 0.4870 - val_loss: 1.0439
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6564 - loss: 0.8018 - val_accuracy: 0.5065 - val_loss: 0.9342
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6694 - loss: 0.6948 - val_accuracy: 0.6104 - val_loss: 0.8670
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6824 - loss: 0.6944 - val_accuracy: 0.5974 - val_loss: 0.8630
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6564 - loss: 0.6833 - val_accuracy: 0.6169 - val_loss: 0.8654
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6792 - loss: 0.6745 - val_accuracy: 0.6039 - val_loss: 0.8858
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6808 - loss: 0.7025 - val_accuracy: 0.5584 - val_loss: 0.9050
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.7331 - val_accuracy: 0.5974 - val_loss: 0.8542
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6824 - loss: 0.6874 - val_accuracy: 0.5649 - val_loss: 0.8859
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6466 - loss: 0.7605 - val_accuracy: 0.5584 - val_loss: 0.8981
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6466 - loss: 0.7166 - val_accuracy: 0.6169 - val_loss: 0.8787
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6873 - loss: 0.6532 - val_accuracy: 0.6039 - val_loss: 0.8381
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7003 - loss: 0.6373 - val_accuracy: 0.5974 - val_loss: 0.8447
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.7041 - val_accuracy: 0.6104 - val_loss: 0.9985
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.7381 - val_accuracy: 0.5195 - val_loss: 0.9330
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6531 - loss: 0.6943 - val_accuracy: 0.6234 - val_loss: 0.8573
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6726 - loss: 0.6402 - val_accuracy: 0.6429 - val_loss: 0.8383
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6873 - loss: 0.6578 - val_accuracy: 0.6104 - val_loss: 0.8164
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6726 - loss: 0.6637 - val_accuracy: 0.6429 - val_loss: 0.8413
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6938 - loss: 0.6308 - val_accuracy: 0.6299 - val_loss: 0.8270
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6987 - loss: 0.6361 - val_accuracy: 0.6364 - val_loss: 0.8270
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6417 - loss: 0.6560 - val_accuracy: 0.6104 - val_loss: 0.8539
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6857 - loss: 0.6256 - val_accuracy: 0.6104 - val_loss: 0.8196
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6971 - loss: 0.6281 - val_accuracy: 0.6234 - val_loss: 0.8234
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7134 - loss: 0.6211 - val_accuracy: 0.6429 - val_loss: 0.8036
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6840 - loss: 0.6748 - val_accuracy: 0.5909 - val_loss: 0.8255
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6792 - loss: 0.6166 - val_accuracy: 0.5909 - val_loss: 0.8248
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6743 - loss: 0.6906 - val_accuracy: 0.5909 - val_loss: 0.8247
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7003 - loss: 0.6265 - val_accuracy: 0.6364 - val_loss: 0.8031
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7134 - loss: 0.6054 - val_accuracy: 0.5455 - val_loss: 0.8730
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6840 - loss: 0.6605 - val_accuracy: 0.6169 - val_loss: 0.9336
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6922 - loss: 0.6303 - val_accuracy: 0.6364 - val_loss: 0.8061
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7166 - loss: 0.5905 - val_accuracy: 0.5844 - val_loss: 0.8458
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7052 - loss: 0.6068 - val_accuracy: 0.6558 - val_loss: 0.8065
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7182 - loss: 0.5897 - val_accuracy: 0.6623 - val_loss: 0.8030
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7085 - loss: 0.6008 - val_accuracy: 0.6688 - val_loss: 0.8026
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6971 - loss: 0.6109 - val_accuracy: 0.6429 - val_loss: 0.8090
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7150 - loss: 0.5840 - val_accuracy: 0.6494 - val_loss: 0.7962
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5841 - val_accuracy: 0.6688 - val_loss: 0.7890
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7036 - loss: 0.6435 - val_accuracy: 0.6494 - val_loss: 0.8265
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7036 - loss: 0.5907 - val_accuracy: 0.5455 - val_loss: 0.9519
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6759 - loss: 0.6462 - val_accuracy: 0.6299 - val_loss: 0.8931
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.5999 - val_accuracy: 0.6494 - val_loss: 0.8177
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6726 - loss: 0.6351 - val_accuracy: 0.6818 - val_loss: 0.7998
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.5785 - val_accuracy: 0.6364 - val_loss: 0.8142
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.5914 - val_accuracy: 0.6688 - val_loss: 0.8147
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6954 - loss: 0.6018 - val_accuracy: 0.6558 - val_loss: 0.8642
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.6039 - val_accuracy: 0.6688 - val_loss: 0.7882
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5945 - val_accuracy: 0.6818 - val_loss: 0.7835
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5981 - val_accuracy: 0.6753 - val_loss: 0.7989
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5690 - val_accuracy: 0.6429 - val_loss: 0.8014
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6564 - loss: 0.6894 - val_accuracy: 0.5909 - val_loss: 0.8784
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6857 - loss: 0.6391 - val_accuracy: 0.6623 - val_loss: 0.7964
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7068 - loss: 0.5730 - val_accuracy: 0.5779 - val_loss: 0.8546
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6808 - loss: 0.6024 - val_accuracy: 0.6558 - val_loss: 0.8387
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7052 - loss: 0.6017 - val_accuracy: 0.6039 - val_loss: 0.8218
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7166 - loss: 0.6011 - val_accuracy: 0.6818 - val_loss: 0.7870
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5809 - val_accuracy: 0.6494 - val_loss: 0.8207
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5655 - val_accuracy: 0.5909 - val_loss: 0.8675
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6873 - loss: 0.5805 - val_accuracy: 0.6818 - val_loss: 0.8046
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7166 - loss: 0.5728 - val_accuracy: 0.6494 - val_loss: 0.7845
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7215 - loss: 0.5618 - val_accuracy: 0.6494 - val_loss: 0.8049
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6906 - loss: 0.5761 - val_accuracy: 0.6234 - val_loss: 0.8315
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7052 - loss: 0.5793 - val_accuracy: 0.6558 - val_loss: 0.8351
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5788 - val_accuracy: 0.6104 - val_loss: 0.8186
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7182 - loss: 0.5800 - val_accuracy: 0.6494 - val_loss: 0.8285
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5770 - val_accuracy: 0.6753 - val_loss: 0.7848
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7182 - loss: 0.5928 - val_accuracy: 0.6818 - val_loss: 0.8051
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6971 - loss: 0.5873 - val_accuracy: 0.6623 - val_loss: 0.8129
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7101 - loss: 0.5783 - val_accuracy: 0.6883 - val_loss: 0.7882
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6954 - loss: 0.5755 - val_accuracy: 0.6753 - val_loss: 0.7884
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7150 - loss: 0.5579 - val_accuracy: 0.6169 - val_loss: 0.8437
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7329 - loss: 0.5721 - val_accuracy: 0.6753 - val_loss: 0.7948
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7296 - loss: 0.5556 - val_accuracy: 0.6429 - val_loss: 0.8162
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6873 - loss: 0.6001 - val_accuracy: 0.6818 - val_loss: 0.7957
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7085 - loss: 0.5780 - val_accuracy: 0.7078 - val_loss: 0.8119
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6906 - loss: 0.5973 - val_accuracy: 0.6818 - val_loss: 0.7899
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7329 - loss: 0.5615 - val_accuracy: 0.6948 - val_loss: 0.8108
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7003 - loss: 0.5699 - val_accuracy: 0.6948 - val_loss: 0.7946
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.5699 - val_accuracy: 0.6948 - val_loss: 0.8106
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5728 - val_accuracy: 0.6494 - val_loss: 0.8301
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.5572 - val_accuracy: 0.6169 - val_loss: 0.8546
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6661 - loss: 0.6738 - val_accuracy: 0.6494 - val_loss: 1.0534
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6710 - loss: 0.6925 - val_accuracy: 0.6818 - val_loss: 0.8244
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7443 - loss: 0.5503 - val_accuracy: 0.6753 - val_loss: 0.8031
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5483 - val_accuracy: 0.7078 - val_loss: 0.7969

In [14]:
#1. how to select appropriate optimizer
#2. no. of nodes in a layer
#3. how to select no. of layers
#4. all in one model

In [16]:
pip install keras-tuner --upgrade

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (26.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (1.83.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.13/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (2.1.3)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 4.0 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [17]:
import kerastuner as kt

/tmp/ipykernel_3944/1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [21]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values = ['adam','rmsprop','sgd','adadelta'])

  model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [22]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [23]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 4 Complete [00h 00m 03s]
val_accuracy: 0.6103895902633667

Best val_accuracy So Far: 0.6103895902633667
Total elapsed time: 00h 01m 04s

In [24]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [25]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [26]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=5,validation_data=(X_test,y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.5831 - loss: 1.9660 - val_accuracy: 0.4675 - val_loss: 2.5908
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5879 - loss: 1.7206 - val_accuracy: 0.6104 - val_loss: 1.7815
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5993 - loss: 1.4708 - val_accuracy: 0.6104 - val_loss: 1.6193
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6140 - loss: 1.3715 - val_accuracy: 0.6558 - val_loss: 1.6835
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6205 - loss: 1.2349 - val_accuracy: 0.6429 - val_loss: 1.3990
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6124 - loss: 1.1461 - val_accuracy: 0.5649 - val_loss: 1.2524
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6417 - loss: 0.9853 - val_accuracy: 0.6558 - val_loss: 1.2844
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6254 - loss: 0.9819 - val_accuracy: 0.5649 - val_loss: 1.0638
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6710 - loss: 0.8996 - val_accuracy: 0.5325 - val_loss: 1.0577
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.8751 - val_accuracy: 0.6818 - val_loss: 1.2175
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6629 - loss: 0.8379 - val_accuracy: 0.6818 - val_loss: 0.9905
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6808 - loss: 0.7999 - val_accuracy: 0.6494 - val_loss: 1.6809
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6726 - loss: 0.8040 - val_accuracy: 0.6753 - val_loss: 0.9482
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6792 - loss: 0.7601 - val_accuracy: 0.5844 - val_loss: 1.1079
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6889 - loss: 0.7657 - val_accuracy: 0.5649 - val_loss: 0.9200
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6433 - loss: 0.7719 - val_accuracy: 0.6688 - val_loss: 0.9203
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6873 - loss: 0.6842 - val_accuracy: 0.5584 - val_loss: 0.9001
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6840 - loss: 0.7407 - val_accuracy: 0.6494 - val_loss: 1.5497
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6889 - loss: 0.7185 - val_accuracy: 0.6104 - val_loss: 0.9968
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7020 - loss: 0.7002 - val_accuracy: 0.4740 - val_loss: 1.5458
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6873 - loss: 0.7273 - val_accuracy: 0.5519 - val_loss: 1.0983
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6938 - loss: 0.6682 - val_accuracy: 0.6948 - val_loss: 0.8662
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6710 - loss: 0.6833 - val_accuracy: 0.6234 - val_loss: 0.9529
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6889 - loss: 0.6790 - val_accuracy: 0.6494 - val_loss: 1.3849
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.7106 - val_accuracy: 0.5779 - val_loss: 0.8811
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6987 - loss: 0.6517 - val_accuracy: 0.6494 - val_loss: 1.4374
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6759 - loss: 0.7260 - val_accuracy: 0.6104 - val_loss: 0.8975
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6792 - loss: 0.6834 - val_accuracy: 0.6688 - val_loss: 1.1441
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6775 - loss: 0.7097 - val_accuracy: 0.5844 - val_loss: 0.8546
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6954 - loss: 0.6527 - val_accuracy: 0.6753 - val_loss: 0.9411
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.6405 - val_accuracy: 0.6558 - val_loss: 1.0339
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6906 - loss: 0.6624 - val_accuracy: 0.7078 - val_loss: 0.9112
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6987 - loss: 0.6504 - val_accuracy: 0.6234 - val_loss: 0.8774
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6824 - loss: 0.6704 - val_accuracy: 0.7078 - val_loss: 0.8823
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6808 - loss: 0.6521 - val_accuracy: 0.5584 - val_loss: 0.9794
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6792 - loss: 0.6592 - val_accuracy: 0.6948 - val_loss: 0.8380
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7020 - loss: 0.6445 - val_accuracy: 0.6883 - val_loss: 0.9024
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6808 - loss: 0.6770 - val_accuracy: 0.6494 - val_loss: 0.8278
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.6247 - val_accuracy: 0.6299 - val_loss: 0.8771
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6808 - loss: 0.6800 - val_accuracy: 0.5779 - val_loss: 0.9250
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6922 - loss: 0.6541 - val_accuracy: 0.5195 - val_loss: 1.0627
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7068 - loss: 0.6087 - val_accuracy: 0.6429 - val_loss: 0.7866
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6938 - loss: 0.6484 - val_accuracy: 0.6623 - val_loss: 1.0771
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.6363 - val_accuracy: 0.6494 - val_loss: 0.7847
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6678 - loss: 0.6251 - val_accuracy: 0.6818 - val_loss: 0.9369
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6889 - loss: 0.6498 - val_accuracy: 0.5974 - val_loss: 0.8499
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6873 - loss: 0.6479 - val_accuracy: 0.5000 - val_loss: 1.0984
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6938 - loss: 0.6211 - val_accuracy: 0.6688 - val_loss: 0.9964
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6889 - loss: 0.6161 - val_accuracy: 0.6753 - val_loss: 0.8532
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6726 - loss: 0.6583 - val_accuracy: 0.6623 - val_loss: 0.8917
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6743 - loss: 0.6547 - val_accuracy: 0.6364 - val_loss: 0.7812
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.6207 - val_accuracy: 0.6104 - val_loss: 0.8002
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6873 - loss: 0.6150 - val_accuracy: 0.5065 - val_loss: 1.0859
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6938 - loss: 0.6455 - val_accuracy: 0.4740 - val_loss: 1.3905
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7020 - loss: 0.6048 - val_accuracy: 0.6883 - val_loss: 0.8489
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6694 - loss: 0.6398 - val_accuracy: 0.6623 - val_loss: 0.9164
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6694 - loss: 0.6411 - val_accuracy: 0.6039 - val_loss: 0.8141
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5857 - val_accuracy: 0.5844 - val_loss: 0.8081
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6922 - loss: 0.6334 - val_accuracy: 0.6623 - val_loss: 0.7654
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.6315 - val_accuracy: 0.6558 - val_loss: 1.2194
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6873 - loss: 0.6393 - val_accuracy: 0.5844 - val_loss: 0.8493
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6954 - loss: 0.5958 - val_accuracy: 0.6623 - val_loss: 0.7917
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7264 - loss: 0.6128 - val_accuracy: 0.6818 - val_loss: 1.0744
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.6198 - val_accuracy: 0.5325 - val_loss: 1.0064
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6873 - loss: 0.6489 - val_accuracy: 0.6234 - val_loss: 0.7880
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.5870 - val_accuracy: 0.6688 - val_loss: 0.9389
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7036 - loss: 0.6364 - val_accuracy: 0.6688 - val_loss: 0.9916
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6857 - loss: 0.6063 - val_accuracy: 0.5519 - val_loss: 1.0301
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.6049 - val_accuracy: 0.5779 - val_loss: 0.9321
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6840 - loss: 0.6280 - val_accuracy: 0.6558 - val_loss: 1.0826
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6954 - loss: 0.6277 - val_accuracy: 0.6429 - val_loss: 1.4981
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7117 - loss: 0.6072 - val_accuracy: 0.6688 - val_loss: 0.9182
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6954 - loss: 0.6078 - val_accuracy: 0.6688 - val_loss: 0.8764
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6889 - loss: 0.6102 - val_accuracy: 0.5065 - val_loss: 1.2865
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5880 - val_accuracy: 0.6688 - val_loss: 0.9647
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.6204 - val_accuracy: 0.7273 - val_loss: 0.7539
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.6000 - val_accuracy: 0.4156 - val_loss: 1.7569
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.6352 - val_accuracy: 0.6494 - val_loss: 1.3345
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6906 - loss: 0.6315 - val_accuracy: 0.6818 - val_loss: 0.7485
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.6019 - val_accuracy: 0.6688 - val_loss: 0.7554
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7036 - loss: 0.6095 - val_accuracy: 0.6753 - val_loss: 0.8473
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7199 - loss: 0.6004 - val_accuracy: 0.6558 - val_loss: 1.0939
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5852 - val_accuracy: 0.5584 - val_loss: 0.9655
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.6015 - val_accuracy: 0.6623 - val_loss: 1.1750
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5675 - val_accuracy: 0.6494 - val_loss: 1.3675
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6954 - loss: 0.6118 - val_accuracy: 0.7403 - val_loss: 0.7604
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7231 - loss: 0.5810 - val_accuracy: 0.7208 - val_loss: 0.7630
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6938 - loss: 0.6114 - val_accuracy: 0.6558 - val_loss: 1.2331
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7068 - loss: 0.6023 - val_accuracy: 0.6818 - val_loss: 0.8156
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6971 - loss: 0.5860 - val_accuracy: 0.6948 - val_loss: 0.8393
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7101 - loss: 0.6041 - val_accuracy: 0.5649 - val_loss: 0.8684
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6906 - loss: 0.6153 - val_accuracy: 0.6688 - val_loss: 0.9305
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7134 - loss: 0.5680 - val_accuracy: 0.7143 - val_loss: 0.7791
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7068 - loss: 0.5819 - val_accuracy: 0.6234 - val_loss: 0.8821
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7134 - loss: 0.5936 - val_accuracy: 0.5779 - val_loss: 0.8861

In [30]:
def build_model(hp):
  model = Sequential()
  units = hp.Int('units', min_value=8, max_value = 128, step=8)

  model.add(Dense(units=units,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [31]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5,directory='mydir',project_name='SK')

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [32]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.6298701167106628

Best val_accuracy So Far: 0.6623376607894897
Total elapsed time: 00h 00m 16s

In [33]:
tuner.get_best_hyperparameters()[0].values

{'units': 120}

In [34]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [35]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=5)

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5977 - loss: 1.3516
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6319 - loss: 1.0078
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6368 - loss: 0.9481
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6059 - loss: 1.0613
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6173 - loss: 0.9598
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6319 - loss: 0.9713
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6352 - loss: 0.9317
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6531 - loss: 0.8441
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6482 - loss: 0.8935
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6270 - loss: 0.9968
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6401 - loss: 0.8638
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6401 - loss: 0.9143
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6873 - loss: 0.7928
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6287 - loss: 0.9285
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6775 - loss: 0.8018
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6368 - loss: 0.9520
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6596 - loss: 0.7768
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6352 - loss: 0.9262
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6596 - loss: 0.8167
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6156 - loss: 0.9911
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6450 - loss: 0.8178
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6433 - loss: 0.8930
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6743 - loss: 0.8225
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 0.8301
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6726 - loss: 0.7756
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6498 - loss: 0.8910
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 0.7786
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6612 - loss: 0.8727
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6173 - loss: 0.9071
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6694 - loss: 0.7768
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6303 - loss: 0.8965
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6547 - loss: 0.8285
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6466 - loss: 0.8880
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6515 - loss: 0.8099
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6580 - loss: 0.8118
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.8352
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6710 - loss: 0.7717
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6401 - loss: 0.8250
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6759 - loss: 0.7916
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6515 - loss: 0.8842
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6694 - loss: 0.7778
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6775 - loss: 0.8627
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6629 - loss: 0.8258
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6547 - loss: 0.7814
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7068 - loss: 0.7770
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.8036
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6466 - loss: 0.9204
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7085 - loss: 0.7337
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6726 - loss: 0.8425
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7085 - loss: 0.7104
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6336 - loss: 0.8964
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6694 - loss: 0.7870
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6743 - loss: 0.8215
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6792 - loss: 0.7430
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6792 - loss: 0.8159
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6564 - loss: 0.8235
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6417 - loss: 0.8786
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6906 - loss: 0.7666
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6840 - loss: 0.8065
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6726 - loss: 0.7467
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6759 - loss: 0.7491
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6938 - loss: 0.8145
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6726 - loss: 0.7335
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6466 - loss: 0.9219
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6954 - loss: 0.8384
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6694 - loss: 0.8098
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7052 - loss: 0.6943
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6954 - loss: 0.6727
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6743 - loss: 0.7921
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6873 - loss: 0.7259
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6498 - loss: 0.7935
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7150 - loss: 0.6516
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6710 - loss: 0.7909
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7003 - loss: 0.6975
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6694 - loss: 0.8021
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6987 - loss: 0.6850
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6873 - loss: 0.7088
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7248 - loss: 0.7266
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6873 - loss: 0.8152
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7020 - loss: 0.6965
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7003 - loss: 0.7585
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7003 - loss: 0.7564
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6922 - loss: 0.7496
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6824 - loss: 0.7315
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6889 - loss: 0.7454
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7036 - loss: 0.7519
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6759 - loss: 0.7843
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6743 - loss: 0.7230
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6824 - loss: 0.7088
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7003 - loss: 0.6802
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6792 - loss: 0.7247
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6612 - loss: 0.7796
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7003 - loss: 0.6740
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6840 - loss: 0.7790
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6775 - loss: 0.7607

In [36]:
def build_model(hp):

  model = Sequential()
  model.add(Dense(72,activation='relu',input_dim=8))
  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    model.add(Dense(72,activation='relu'))

  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [37]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=3, directory='mydir', project_name='srk')

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [38]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.649350643157959

Best val_accuracy So Far: 0.649350643157959
Total elapsed time: 00h 00m 12s

In [39]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3}

In [40]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 12 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [41]:
model.fit(X_train,y_train,epochs=100,initial_epoch=5,validation_data=(X_test,y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 0.6303 - loss: 0.8217 - val_accuracy: 0.3831 - val_loss: 1.2651
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6417 - loss: 0.7062 - val_accuracy: 0.6429 - val_loss: 0.7220
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6954 - loss: 0.5918 - val_accuracy: 0.5584 - val_loss: 0.8970
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6759 - loss: 0.6520 - val_accuracy: 0.6494 - val_loss: 0.7565
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.5998 - val_accuracy: 0.6429 - val_loss: 0.7979
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6629 - loss: 0.6134 - val_accuracy: 0.5909 - val_loss: 0.8096
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6759 - loss: 0.6097 - val_accuracy: 0.5649 - val_loss: 0.7699
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.5902 - val_accuracy: 0.6494 - val_loss: 0.7362
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6596 - loss: 0.6032 - val_accuracy: 0.5909 - val_loss: 0.8543
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7166 - loss: 0.5726 - val_accuracy: 0.5909 - val_loss: 0.8328
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.5920 - val_accuracy: 0.6039 - val_loss: 0.8495
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6906 - loss: 0.5733 - val_accuracy: 0.6558 - val_loss: 0.7587
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7020 - loss: 0.5724 - val_accuracy: 0.6623 - val_loss: 0.7947
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.5616 - val_accuracy: 0.6169 - val_loss: 0.7893
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7199 - loss: 0.5383 - val_accuracy: 0.5844 - val_loss: 0.8617
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.5631 - val_accuracy: 0.6623 - val_loss: 0.8419
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7264 - loss: 0.5454 - val_accuracy: 0.6494 - val_loss: 0.9399
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7264 - loss: 0.5518 - val_accuracy: 0.6558 - val_loss: 0.9899
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7003 - loss: 0.5599 - val_accuracy: 0.6429 - val_loss: 0.8584
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5455 - val_accuracy: 0.6558 - val_loss: 0.7991
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5461 - val_accuracy: 0.7078 - val_loss: 0.8004
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5286 - val_accuracy: 0.6818 - val_loss: 0.8265
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5269 - val_accuracy: 0.6883 - val_loss: 0.7675
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5345 - val_accuracy: 0.6753 - val_loss: 0.8581
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5331 - val_accuracy: 0.6883 - val_loss: 0.7609
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5293 - val_accuracy: 0.6883 - val_loss: 0.7601
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5120 - val_accuracy: 0.5974 - val_loss: 0.8572
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5108 - val_accuracy: 0.4675 - val_loss: 1.0088
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.5274 - val_accuracy: 0.6688 - val_loss: 0.8329
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5234 - val_accuracy: 0.6364 - val_loss: 1.0649
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5333 - val_accuracy: 0.6234 - val_loss: 0.8048
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5006 - val_accuracy: 0.6948 - val_loss: 0.8213
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5039 - val_accuracy: 0.5974 - val_loss: 0.9542
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5018 - val_accuracy: 0.6688 - val_loss: 0.8763
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5083 - val_accuracy: 0.6623 - val_loss: 0.9477
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5116 - val_accuracy: 0.6818 - val_loss: 0.8149
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.4789 - val_accuracy: 0.6948 - val_loss: 0.8985
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4939 - val_accuracy: 0.7013 - val_loss: 0.9077
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4832 - val_accuracy: 0.7078 - val_loss: 0.8096
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4786 - val_accuracy: 0.6558 - val_loss: 0.9231
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4781 - val_accuracy: 0.7143 - val_loss: 0.8170
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4789 - val_accuracy: 0.6883 - val_loss: 0.8492
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4766 - val_accuracy: 0.6883 - val_loss: 0.9084
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4790 - val_accuracy: 0.6429 - val_loss: 0.9273
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4656 - val_accuracy: 0.5519 - val_loss: 0.9918
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4844 - val_accuracy: 0.5974 - val_loss: 0.9528
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4757 - val_accuracy: 0.7078 - val_loss: 0.9114
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4793 - val_accuracy: 0.7013 - val_loss: 0.9600
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4723 - val_accuracy: 0.6883 - val_loss: 0.9685
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7655 - loss: 0.4478 - val_accuracy: 0.6364 - val_loss: 1.0186
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4539 - val_accuracy: 0.5584 - val_loss: 1.0400
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4514 - val_accuracy: 0.6429 - val_loss: 1.1014
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4636 - val_accuracy: 0.6818 - val_loss: 1.0669
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4491 - val_accuracy: 0.7273 - val_loss: 1.1055
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4531 - val_accuracy: 0.7338 - val_loss: 1.1254
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4454 - val_accuracy: 0.7013 - val_loss: 1.0182
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4592 - val_accuracy: 0.7532 - val_loss: 1.0228
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4462 - val_accuracy: 0.6948 - val_loss: 1.0684
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4500 - val_accuracy: 0.6883 - val_loss: 1.0631
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4262 - val_accuracy: 0.6494 - val_loss: 1.3959
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4528 - val_accuracy: 0.5909 - val_loss: 1.1827
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4341 - val_accuracy: 0.6883 - val_loss: 1.0949
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4347 - val_accuracy: 0.6818 - val_loss: 1.2891
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4463 - val_accuracy: 0.6558 - val_loss: 1.0726
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8046 - loss: 0.4223 - val_accuracy: 0.7143 - val_loss: 1.2631
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8111 - loss: 0.4145 - val_accuracy: 0.7143 - val_loss: 1.1871
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7997 - loss: 0.4384 - val_accuracy: 0.7013 - val_loss: 1.1749
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8062 - loss: 0.4285 - val_accuracy: 0.6948 - val_loss: 1.1279
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4187 - val_accuracy: 0.7078 - val_loss: 1.1532
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8078 - loss: 0.4263 - val_accuracy: 0.6623 - val_loss: 1.2801
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4222 - val_accuracy: 0.7273 - val_loss: 1.2124
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8078 - loss: 0.4188 - val_accuracy: 0.6558 - val_loss: 1.3266
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4254 - val_accuracy: 0.6623 - val_loss: 1.2849
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8306 - loss: 0.3896 - val_accuracy: 0.6623 - val_loss: 1.5317
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8192 - loss: 0.4123 - val_accuracy: 0.7078 - val_loss: 1.2635
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4003 - val_accuracy: 0.7338 - val_loss: 1.3376
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4047 - val_accuracy: 0.6299 - val_loss: 1.4186
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4162 - val_accuracy: 0.6753 - val_loss: 1.3336
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4083 - val_accuracy: 0.7143 - val_loss: 1.3379
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4021 - val_accuracy: 0.7078 - val_loss: 1.4660
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.4002 - val_accuracy: 0.6039 - val_loss: 1.4562
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3918 - val_accuracy: 0.6688 - val_loss: 1.3279
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3996 - val_accuracy: 0.6169 - val_loss: 1.5250
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3939 - val_accuracy: 0.7208 - val_loss: 1.4419
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3942 - val_accuracy: 0.6429 - val_loss: 1.4593
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.3905 - val_accuracy: 0.6688 - val_loss: 1.3651
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3984 - val_accuracy: 0.6883 - val_loss: 1.4819
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3939 - val_accuracy: 0.7078 - val_loss: 1.4832
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3842 - val_accuracy: 0.6299 - val_loss: 1.5128
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4036 - val_accuracy: 0.6623 - val_loss: 1.5409
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8290 - loss: 0.3829 - val_accuracy: 0.7338 - val_loss: 1.6444
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3933 - val_accuracy: 0.7078 - val_loss: 1.6333
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3856 - val_accuracy: 0.6688 - val_loss: 1.4659
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3611 - val_accuracy: 0.7013 - val_loss: 1.6286
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3753 - val_accuracy: 0.6299 - val_loss: 1.6932

In [55]:
def build_model(hp):
  model = Sequential()

  counter = 0;

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):

    if counter == 0:

      model.add(
          Dense(
              hp.Int('units' + str(i), min_value=8, max_value=128,step=8),
              activation=hp.Choice('activation' + str(i), values = ['relu', 'tanh', 'sigmoid']),
              input_dim=8
              )
          )
      model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    else:
      model.add(
          Dense(
              hp.Int('units' + str(i), min_value=8, max_value=128,step=8),
              activation=hp.Choice('activation' + str(i), values = ['relu', 'tanh', 'sigmoid'])
              )
          )
      model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))

    counter+=1

  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer', values = ['rmsprop','adam','sgd','nadam','adadelta']),
              loss='binary_crossentropy',
              metrics=['accuracy'])

  return model

In [56]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=3,directory='my_dir',project_name='final1')

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [57]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 07s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.6428571343421936
Total elapsed time: 00h 00m 18s

In [58]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4,
 'units0': 16,
 'activation0': 'tanh',
 'dropout0': 0.5,
 'optimizer': 'nadam',
 'units1': 8,
 'activation1': 'relu',
 'dropout1': 0.1,
 'units2': 8,
 'activation2': 'relu',
 'dropout2': 0.1,
 'units3': 8,
 'activation3': 'relu',
 'dropout3': 0.1}

In [59]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'nadam', because it has 2 variables whereas the saved optimizer has 23 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [60]:
model.fit(X_train,y_train,epochs=100,initial_epoch=5,validation_data=(X_test,y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - accuracy: 0.6401 - loss: 0.6751 - val_accuracy: 0.6429 - val_loss: 0.6725
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6450 - loss: 0.6756 - val_accuracy: 0.6429 - val_loss: 0.6682
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6603 - val_accuracy: 0.6429 - val_loss: 0.6635
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.6557 - val_accuracy: 0.6429 - val_loss: 0.6604
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6565 - val_accuracy: 0.6429 - val_loss: 0.6596
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6448 - val_accuracy: 0.6429 - val_loss: 0.6590
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6587 - val_accuracy: 0.6429 - val_loss: 0.6566
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6482 - loss: 0.6469 - val_accuracy: 0.6429 - val_loss: 0.6564
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.6489 - val_accuracy: 0.6429 - val_loss: 0.6571
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6471 - val_accuracy: 0.6429 - val_loss: 0.6565
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6493 - val_accuracy: 0.6429 - val_loss: 0.6574
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6468 - val_accuracy: 0.6429 - val_loss: 0.6571
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.6442 - val_accuracy: 0.6429 - val_loss: 0.6574
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6387 - val_accuracy: 0.6429 - val_loss: 0.6575
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6547 - loss: 0.6442 - val_accuracy: 0.6429 - val_loss: 0.6560
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6467 - val_accuracy: 0.6429 - val_loss: 0.6559
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6393 - val_accuracy: 0.6429 - val_loss: 0.6550
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6395 - val_accuracy: 0.6429 - val_loss: 0.6544
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6491 - val_accuracy: 0.6429 - val_loss: 0.6527
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6272 - val_accuracy: 0.6429 - val_loss: 0.6503
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6401 - val_accuracy: 0.6429 - val_loss: 0.6498
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6547 - loss: 0.6360 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6366 - val_accuracy: 0.6429 - val_loss: 0.6528
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6340 - val_accuracy: 0.6429 - val_loss: 0.6490
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6376 - val_accuracy: 0.6429 - val_loss: 0.6494
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6370 - val_accuracy: 0.6429 - val_loss: 0.6507
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6264 - val_accuracy: 0.6429 - val_loss: 0.6448
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.6310 - val_accuracy: 0.6429 - val_loss: 0.6451
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6547 - loss: 0.6315 - val_accuracy: 0.6429 - val_loss: 0.6447
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6424 - val_accuracy: 0.6429 - val_loss: 0.6462
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6393 - val_accuracy: 0.6429 - val_loss: 0.6463
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6423 - val_accuracy: 0.6429 - val_loss: 0.6466
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6331 - val_accuracy: 0.6429 - val_loss: 0.6479
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.6355 - val_accuracy: 0.6429 - val_loss: 0.6490
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6466 - loss: 0.6312 - val_accuracy: 0.6429 - val_loss: 0.6491
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6498 - loss: 0.6277 - val_accuracy: 0.6429 - val_loss: 0.6434
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.6331 - val_accuracy: 0.6429 - val_loss: 0.6418
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6293 - val_accuracy: 0.6429 - val_loss: 0.6417
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6260 - val_accuracy: 0.6429 - val_loss: 0.6464
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6318 - val_accuracy: 0.6429 - val_loss: 0.6453
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6310 - val_accuracy: 0.6429 - val_loss: 0.6410
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6482 - loss: 0.6295 - val_accuracy: 0.6429 - val_loss: 0.6421
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6547 - loss: 0.6296 - val_accuracy: 0.6429 - val_loss: 0.6420
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6252 - val_accuracy: 0.6429 - val_loss: 0.6412
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6291 - val_accuracy: 0.6429 - val_loss: 0.6432
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6316 - val_accuracy: 0.6429 - val_loss: 0.6454
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6482 - loss: 0.6340 - val_accuracy: 0.6429 - val_loss: 0.6437
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6291 - val_accuracy: 0.6429 - val_loss: 0.6432
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6186 - val_accuracy: 0.6429 - val_loss: 0.6421
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.6268 - val_accuracy: 0.6429 - val_loss: 0.6429
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6285 - val_accuracy: 0.6429 - val_loss: 0.6414
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.6350 - val_accuracy: 0.6429 - val_loss: 0.6446
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6307 - val_accuracy: 0.6429 - val_loss: 0.6440
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6303 - val_accuracy: 0.6429 - val_loss: 0.6445
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.6287 - val_accuracy: 0.6429 - val_loss: 0.6447
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.6263 - val_accuracy: 0.6429 - val_loss: 0.6412
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6547 - loss: 0.6231 - val_accuracy: 0.6429 - val_loss: 0.6401
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6131 - val_accuracy: 0.6429 - val_loss: 0.6384
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6207 - val_accuracy: 0.6429 - val_loss: 0.6390
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.6158 - val_accuracy: 0.6429 - val_loss: 0.6382
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6450 - loss: 0.6336 - val_accuracy: 0.6429 - val_loss: 0.6369
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6130 - val_accuracy: 0.6429 - val_loss: 0.6365
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6580 - loss: 0.6226 - val_accuracy: 0.6429 - val_loss: 0.6341
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6155 - val_accuracy: 0.6429 - val_loss: 0.6334
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6515 - loss: 0.6168 - val_accuracy: 0.6429 - val_loss: 0.6310
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6482 - loss: 0.6150 - val_accuracy: 0.6429 - val_loss: 0.6305
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6531 - loss: 0.6296 - val_accuracy: 0.6429 - val_loss: 0.6310
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6482 - loss: 0.6226 - val_accuracy: 0.6429 - val_loss: 0.6298
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6515 - loss: 0.6311 - val_accuracy: 0.6429 - val_loss: 0.6304
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6531 - loss: 0.6244 - val_accuracy: 0.6429 - val_loss: 0.6308
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6482 - loss: 0.6178 - val_accuracy: 0.6429 - val_loss: 0.6314
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6531 - loss: 0.6106 - val_accuracy: 0.6429 - val_loss: 0.6307
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6596 - loss: 0.6131 - val_accuracy: 0.6429 - val_loss: 0.6311
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6482 - loss: 0.6161 - val_accuracy: 0.6429 - val_loss: 0.6283
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6564 - loss: 0.6084 - val_accuracy: 0.6429 - val_loss: 0.6277
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6128 - val_accuracy: 0.6429 - val_loss: 0.6308
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6417 - loss: 0.6176 - val_accuracy: 0.6429 - val_loss: 0.6303
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6596 - loss: 0.6134 - val_accuracy: 0.6429 - val_loss: 0.6270
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6079 - val_accuracy: 0.6429 - val_loss: 0.6280
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6168 - val_accuracy: 0.6429 - val_loss: 0.6289
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6204 - val_accuracy: 0.6429 - val_loss: 0.6298
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6645 - loss: 0.6101 - val_accuracy: 0.6429 - val_loss: 0.6299
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.5958 - val_accuracy: 0.6494 - val_loss: 0.6311
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.6032 - val_accuracy: 0.6429 - val_loss: 0.6336
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6498 - loss: 0.6099 - val_accuracy: 0.6494 - val_loss: 0.6352
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6112 - val_accuracy: 0.6429 - val_loss: 0.6322
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6612 - loss: 0.6156 - val_accuracy: 0.6429 - val_loss: 0.6325
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6629 - loss: 0.6297 - val_accuracy: 0.6429 - val_loss: 0.6374
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6629 - loss: 0.6104 - val_accuracy: 0.6429 - val_loss: 0.6312
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6006 - val_accuracy: 0.6494 - val_loss: 0.6279
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6029 - val_accuracy: 0.6494 - val_loss: 0.6302
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6433 - loss: 0.6148 - val_accuracy: 0.6494 - val_loss: 0.6321
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6612 - loss: 0.6047 - val_accuracy: 0.6494 - val_loss: 0.6326
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6661 - loss: 0.6095 - val_accuracy: 0.6494 - val_loss: 0.6322
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6547 - loss: 0.6013 - val_accuracy: 0.6494 - val_loss: 0.6269